version: "3.9"

services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - ./docker_data/db:/var/lib/postgresql/data
        ports:
            - ${DB_PORT}:5432
